<?php
include 'kuki.php';
echo "<html lang=\"hu\">\n"; 
echo "<head>\n"; 
echo "<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\n"; 
echo "<title>MT Eszközcsere</title>\n"; 
echo "</head>\n"; 
echo "<body bgcolor=\"#D8D8D8\">\n"; 
echo "<h1>Eszközcsere</h1>\n"; 
echo "\n"; 
echo "<p></p>\n"; 
echo "<form action=\"eszkoz_be.php\" method=\"post\">\n"; 
echo "	<table border=8>\n"; 
echo "	<tr>\n"; 
echo "	<td>\n"; 
echo "	  A szám: </td><td> <input type=\"text\" name=\"a_szam\" />\n"; 
echo "	</td>\n"; 
echo "	</tr>\n"; 
echo "	<tr>\n"; 
echo "	<td>\n"; 
echo "	  Régi eszköz gyári szám: </td><td> <input type=\"text\" name=\"serial1\" />\n"; 
echo "	</td>\n"; 
echo "	</tr>\n"; 
echo "	<tr>\n"; 
echo "	<td>\n"; 
echo "	  Új eszköz gyári szám:  </td><td><input type=\"text\" name=\"serial2\">\n"; 
echo "	</td>\n"; 
echo "	</tr>\n"; 
echo "	</table>\n"; 
echo "	  <!-- Dátum: <input type=\"text\" name=\"date\" /><br />\n"; 
echo "	  -->\n"; 
echo "	<tr>\n"; 
echo "	<td> \n"; 
echo "	  <input type=\"submit\" value=\"Adatok elküldése\" name=\"submit\" />	  \n"; 
echo "	</td>\n"; 
echo "	</tr>\n"; 
echo "	  \n"; 
echo "</form>\n"; 
echo "\n"; 
echo "</body>\n"; 
echo "</html>\n";
?>
